### ISSUE TITLE
Update README.md 

### ISSUE THREAD

**Issue by samarth777** [acmpesuecc/BrainSpark#1]
Update README.md with proper description of the project, usage guide and documentation

**Comment by stealthwhizz** [comment]
can i get this?

**Comment by samarth777** [comment]
> can i get this?

sure assigning you please update me at 8 30 about your progress

**Comment by SavvyHex** [comment]
Can I get assigned to this?

**Comment by stealthwhizz** [comment]
@DedLad ,@polarhive pr not noticed

**Comment by samarth777** [comment]
cool I have merged the PR

**Comment by stealthwhizz** [comment]
> cool I have merged the PR

ggs

**Comment by samarth777** [comment]
closing this issue
