### ISSUE TITLE
Implement Google Auth

### ISSUE THREAD

**Issue by samarth777** [acmpesuecc/BrainSpark#3]
Implement google O auth for signing up and logging in

**Comment by srijan-nodes** [comment]
can I please get this?

**Comment by samarth777** [comment]
sure update me your progress by 8 30

**Comment by srijan-nodes** [comment]
nearly done...getting up for dinner!

**Comment by samarth777** [comment]
cool lmk

**Comment by SavvyHex** [comment]
Can I be assigned to this, if there are no updates from the previous account?

**Comment by srijan-nodes** [comment]
will it be possible that I can meet you? got a small doubt

**Comment by samarth777** [comment]
I am a remote maintainer
so we can hava google meet

**Comment by samarth777** [comment]
send me a link

**Comment by srijan-nodes** [comment]
https://meet.google.com/ssx-tzgo-odg

**Comment by srijan-nodes** [comment]
made a pr

**Comment by samarth777** [comment]
give me 5 min checking if it works

**Comment by samarth777** [comment]
or wait come on call and show me demo

**Comment by samarth777** [comment]
same meet link

**Comment by KaparthyReddy** [comment]
could u assign this
