### ISSUE TITLE
Implement feature to integrate notion and github

### ISSUE THREAD

**Issue by samarth777** [acmpesuecc/BrainSpark#4]
Add a feature where you can integrate Guthub and Notion for an idea

**Comment by SuhaniSinghPES** [comment]
can i get this??

**Comment by stealthwhizz** [comment]
can i get this?

**Comment by samarth777** [comment]
@SuhaniSinghPES any updates?

**Comment by himaniraoo** [comment]
@samarth777 , can i be assigned this ?

**Comment by samarth777** [comment]
sure give me a progress update after a few min

**Comment by himaniraoo** [comment]
@samarth777 , i've added two files to my forked repository , pls extend my time , i'm working on how to put my index.ts under a src file in github

**Comment by himaniraoo** [comment]
@samarth777 , should i pr for 2 files just as is it for a review ?

**Comment by samarth777** [comment]
1 PR is enough for both

**Comment by himaniraoo** [comment]
@samarth777 , did you get a request ?

**Comment by himaniraoo** [comment]
@samarth777 , sorry there was a confusion , i sent a pr now

**Comment by himaniraoo** [comment]
@samarth777 , kindly update me further , rn we have been asked to move to sem hall 2 for some event

**Comment by himaniraoo** [comment]
@samarth777 , can u give me some more time for improvements , i want to try in adding in more ?

**Comment by himaniraoo** [comment]
@samarth777 , i have a small eroror , im trying to create front end too but thats stopping me , pls check with me

**Comment by himaniraoo** [comment]
@samarth777 , i've pulled a request , kindly check it :')

**Comment by himaniraoo** [comment]
@samarth777 , i waited for 6 hours , can i pls get bounty points for whatever i've pulled requests , thanks , i will unassign myself to try new repositories

**Comment by VulcanRaven737** [comment]
Can I please get assigned to this?

**Comment by samarth777** [comment]
@himaniraoo I'll check the PR and give you bounty points

**Comment by himaniraoo** [comment]
thanks ! @samarth777
